version: "3.1"
services:
    mysql:
      image: mysql:5.7
      container_name: php-slim-blog-mysql
      ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}
      volumes:
      - ./docker/mysql-data:/var/lib/mysql
      env_file:
      - .env

    web:
      image: nginx:alpine
      container_name: php-slim-blog-web
      volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
      - ${WEB_PORT}:80
      links:
      - php-fpm

    php-fpm:
      build: ./docker/php-fpm
      container_name: php-slim-blog-php-fpm
      volumes:
        - .:/application
        - ./docker/php-fpm/php-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      links: 
        - mysql:mysql
      extra_hosts:
        - dockerhost:${HOST_IP}
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}